
import "./globals.css";
import { Inter } from "next/font/google";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/public/Navbar"; // make sure this is client component
import Footer from "@/components/public/Footer"; // client component
import Providers from "@/components/providers"; // client component

const inter = Inter({ subsets: ["latin"] });
const geistSans = Geist({ subsets: ["latin"], variable: "--font-geist-sans" });
const geistMono = Geist_Mono({ subsets: ["latin"], variable: "--font-geist-mono" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Navbar />
          <div className="min-h-screen flex flex-col">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
